In [1]:
import pandas as pd

from dpks.quant_matrix import QuantMatrix
from dpks.normalization import RTSlidingWindowNormalization, MeanNormalization

quant_matrix = QuantMatrix(
    quantification_file="../tests/input_files/de_matrix.tsv",
    design_matrix_file="../tests/input_files/de_design_matrix.tsv"
)

In [2]:
filtered_data = quant_matrix.filter()

In [3]:
rt_window_normalization = RTSlidingWindowNormalization(
    base_method=MeanNormalization
)

In [4]:
filtered_data.quantitative_data.X

array([[1.06602e+07, 1.13075e+07, 1.12150e+07, ..., 1.22147e+07,
        1.17110e+07, 1.24860e+07],
       [3.86613e+05, 1.86338e+06, 4.27898e+05, ..., 2.03076e+06,
        4.39037e+05, 2.05356e+06],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       ...,
       [2.74190e+07, 1.41364e+08, 3.06309e+07, ..., 1.47929e+08,
        2.88103e+07, 1.43518e+08],
       [        nan,         nan,         nan, ...,         nan,
        1.36969e+06, 1.56666e+06],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]])

In [5]:
normalized_data = rt_window_normalization.fit_transform(filtered_data)

/home/aaron/projects/dpks/dpks/dpks/normalization.py:108: RuntimeWarning: Mean of empty slice
  sample_means = np.nanmean(X, axis=0)


In [6]:
normalized_data.quantitative_data.X

array([[1.01036962e+07, 1.27967845e+07, 1.23549489e+07, ...,
        1.15900599e+07, 1.07369777e+07, 1.25106019e+07],
       [3.66430300e+05, 2.10880144e+06, 4.71391702e+05, ...,
        1.92691019e+06, 4.02521603e+05, 2.05760625e+06],
       [           nan,            nan,            nan, ...,
                   nan,            nan,            nan],
       ...,
       [2.74190000e+07, 1.41364000e+08, 3.06309000e+07, ...,
        1.47929000e+08, 2.88103000e+07, 1.43518000e+08],
       [           nan,            nan,            nan, ...,
                   nan, 1.36969000e+06, 1.56666000e+06],
       [           nan,            nan,            nan, ...,
                   nan,            nan,            nan]])

In [7]:
from dpks.normalization import Log2Normalization

normalized_data.quantitative_data.X = Log2Normalization().fit_transform(
    normalized_data.quantitative_data.X
)

In [8]:
normalized_data.quantitative_data.X

array([[23.26837983, 23.60927801, 23.55858571, ..., 23.46638468,
        23.35608462, 23.57664787],
       [18.48317928, 21.00799183, 18.84656684, ..., 20.8778579 ,
        18.61870669, 20.9725355 ],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       ...,
       [24.70867262, 27.07483953, 24.86848442, ..., 27.14032967,
        24.78008135, 27.09665645],
       [        nan,         nan,         nan, ...,         nan,
        20.38541798, 20.57926069],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]])